#!/usr/bin/python

from re import findall

def main():
    with open('input', 'r') as fp:
        row, col = findall(r'(\d+)', fp.read())
    
    # The voice on the other end of the phone continues with how the codes are actually generated. The 
    # first code is 20151125. After that, each code is generated by taking the previous one, multiplying 
    # it by 252533, and then keeping the remainder from dividing that value by 33554393.
    initSeed = 2015112




if __name__ == '__main__':
    main()